# Generated by Django 2.2 on 2022-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('react', 'react'), ('designing', 'designing'), ('Bde', 'Bde')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Domain_name',
        ),
    ]
