# Generated by Django 2.2 on 2022-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221228_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('HR', 'HR'), ('MD', 'MD'), ('TL', 'TL'), ('Intern', 'Intern'), ('Employee', 'Employee')], default='Admin', max_length=10, null=True),
        ),
    ]
