# Generated by Django 2.2 on 2022-12-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateField()),
                ('report_till', models.DateField()),
                ('new_reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='New_reporting_to', to=settings.AUTH_USER_MODEL)),
                ('report_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reporting_by', to=settings.AUTH_USER_MODEL)),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reporting_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
