# Generated by Django 2.2 on 2022-12-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221228_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
