# Generated by Django 2.2 on 2022-11-22 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=100)),
                ('user_cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('user', models.CharField(max_length=100)),
                ('domain_interview', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('Sr', 'Sr'), ('Jr', 'Jr'), ('Intern', 'Intern')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('Hold', 'Hold'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Hold', max_length=10)),
                ('attempt', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office_meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Agenda', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('soft_delete', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='user_office_meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
