# Generated by Django 2.2 on 2022-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_meeting',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='domain_interview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='position',
            field=models.CharField(blank=True, choices=[('Sr', 'Sr'), ('Jr', 'Jr'), ('Intern', 'Intern')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='status',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Hold', max_length=10),
        ),
        migrations.AlterField(
            model_name='interview_meeting',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
