# Generated by Django 2.2 on 2022-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20221122_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_meeting',
            name='mode_choice',
            field=models.CharField(blank=True, choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=50, null=True),
        ),
    ]
