# Generated by Django 2.2 on 2022-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20221229_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
