# Generated by Django 2.2 on 2022-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_interview_meeting_mode_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office_meeting',
            name='user',
        ),
        migrations.AddField(
            model_name='office_meeting',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
