# Generated by Django 2.2 on 2022-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20221229_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
