# Generated by Django 2.2 on 2022-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20221229_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
