# Generated by Django 2.2 on 2022-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_leavereportemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='punch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
