# Generated by Django 2.2 on 2022-12-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20221211_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='punch_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
