# Generated by Django 2.2 on 2022-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20221212_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='marked',
            field=models.BooleanField(blank=True, default='in', null=True),
        ),
    ]
