# Generated by Django 2.2 on 2022-12-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20221213_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
