# Generated by Django 2.2 on 2022-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_auto_20221213_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('learning', 'learning'), ('development', 'development'), ('task', 'task'), ('project', 'project'), ('deployment', 'deployment')], max_length=50)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='task/')),
                ('detail', models.TextField()),
            ],
        ),
    ]
