# Generated by Django 2.2 on 2022-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_auto_20221219_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
