# Generated by Django 2.2 on 2022-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_auto_20221226_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
