# Generated by Django 2.2 on 2022-12-26 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_auto_20221226_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='create_task_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 26, 8, 54, 0, 414404, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
