# Generated by Django 2.2 on 2022-12-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_auto_20221226_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_task_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
